### ISSUE TITLE
Token leaked in network tab

### ISSUE THREAD

**Issue by ijaspreetsinghh** [supabase-community/supabase-dart#113] opened 2022-05-15 03:56 UTC
[Supabase ](https://pub.dev/packages/supabase) package for flutter is leaking all the requests, bearer token and request body in network tabs for flutter web. This kind of behaviour is unsecured and anyone can get hijack the app's resources by connecting from their code. or maybe via postman alone. Can this thing be fixed ASAP or is there anything we can do to prevent this leakage from happening?

![image](https://user-images.githubusercontent.com/44422128/168456504-162d227c-497b-4034-ba39-0d336438ce16.png)

**Comment by dshukertjr** [comment] 2022-05-15 04:08
@ijaspreetsinghh Thanks for opening this issue. Let me take a look.

**Comment by dshukertjr** [comment] 2022-05-15 04:21
@ijaspreetsinghh 
This behavior is expected when using JWT for authorization. 

Just because your user has access to your anon key or auth token, it does not mean your resources on the server can be accessed freely as long as you set up row level security.
https://supabase.com/docs/guides/auth/row-level-security

You can read more about JWT and network tab here
https://stackoverflow.com/questions/47402405/jwt-why-is-my-token-shown-in-chrome-devtools

Let me know if you have any questions.

**Comment by dshukertjr** [comment] 2022-07-11 01:01
I would like to close this issue as it is the expected behavior. Please feel free to open issues if anything else comes up in the future!

**Closed by dshukertjr** 2022-07-11 01:01 UTC
